name: Build & Test

on: [push, pull_request]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TERM: xterm
      CC: gcc
    steps:
      - uses: actions/checkout@v7.0.1
      - name: install packages
        run: sudo apt-get install libgtk-3-dev xvfb
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build
        run: rake
      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: mrbmacs-gtk
          path: mruby/bin/mrbmacs-gtk
      - name: Test
        run: xvfb-run rake test

  macOS:
    runs-on: macos-latest
    timeout-minutes: 20
    env:
      CC: clang
    steps:
      - uses: actions/checkout@v7.0.1
      - name: install gtk
        run: |
          brew update
          brew install gtk+3 gtk-mac-integration
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build
        run: rake
      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: mrbmacs-gtk
          path: mruby/bin/mrbmacs-gtk
      - name: Setup faketty
        uses: Yuri6037/Action-FakeTTY@v1.1
      - name: Test
        run: faketty rake test
